# -*- coding: utf-8 -*-
"""NLP1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lUzQeAHf-y6rzjqQN1fJejv8VFqN3nWb
"""

from google.colab import drive                                                           #Mounting Google drive
drive.mount('/content/drive')

path="/content/drive/MyDrive/sem2/Text.txt" # one station csv file                       #path for Text file

import re                                                                                #reading the text file file
file = open(path,"r")
data=file.read()
                                                                                          # adding other date formats
data = data +'\n 18th Jan, 2004' + '\n 14 June, 2000' + '\n 07-11-1991' + '\n 23-03-2003' + '\n 26/11/2008'   +  '\n May 15th, 1987'
data += ' \n 2nd Sep 1994' + '\n 19-February-2004' + '\n 2/10/1994' + '\n 3rd-April, 1965' + '\n 3rd-Mar-1857' + '\n July 2nd, 1847' 
                                                                                         
data

r1=r"\d{1,2}[/-]\d{2}[/-]\d{4}"                                                   #Creating regex for different Date formats 
r2=r"(\d{1,2}[-/th|st|nd|rd\s]*(?:January|February|March|April|May|June|July|August|September|October|November|December)[\s,-]*\d{4})"
r3=r"(\d{1,2}[-/th|st|nd|rd\s]*(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[\s,-]*\d{4})"
r4=r"((?:January|February|March|April|May|June|July|August|September|October|November|December) \d{1,2}[-/th|st|nd|rd\s]*,? \d{4})"

r_list=[r1,r2,r3,r4]                                                              #creating list for all regex

format1,format2,format3,format4=[],[],[],[]                                       #Initializing list for different regex date formats


for i in range(len(dates)):                                                       # extracting dates based on different regex date formats
    dates[i] += re.findall(r_list[i], data)                                        

dates=[format1,format2,format3,format4]                                           # Saving different date formats extracted in list of list

dates

replaced_list_1=[]                                                         #Initializing list for extracted date format 1                                                            

replacement1_dict={                                                        #Creating Dictionary to assist replacement of formats
    '/01/':'-January-','-01-':'-January-','/02/':'-February-','-02-':'-February-','/03/':'-March-','-03-':'-March-','/04/':'-April-',
    '-04-':'-April-','/05/':'-May-', '-05-':'-May-','/06/':'-June-', '-06-':'-June-','/07/':'-July-','-07-':'-July-','/08/':'-August-',
    '-08-':'-August-','/09/':'-Semtember-','-09-':'-Semtember-','/10/':'-October-','-10-':'-October-','/11/':'-November-',
    '-11-':'-November-','/12/':'-December-','-12-':'-December-'
    }

for i in range(len(dates[0])):                                              #replacing date format based on dictionary 
   for j,k in replacement1_dict.items():
     if j in dates[0][i]:
       replaced_list_1.append(dates[0][i].replace(j,k))


print('orignal dates:', dates[0])                                           # Printing orignal and replaced date format.
print('Replaced dates:', replaced_list_1)

replaced_list_2=[]                                                            #Initializing list for extracted date format 2

for i in range(len(dates[1])):                                                #replacing date format using re.sub() with proper regex
    replaced_list_2.append(re.sub("\s|th |nd |rd |th-|nd-|rd-|, ","-",dates[1][i]))

print('orignal dates:', dates[1])                                             # Printing orignal and replaced date format.
print('Replaced dates:', replaced_list_2)



replaced_list_3a=[]                                                  #Initializing two lists for extracted date format 3
replaced_list_3=[]

replacement3_dict={                                                  #Creating Dictionary to assist replacement of formats
    'Jan':'January','Feb':'February','Mar':'March','Apr':'April','May':'May','Jun':'June','Jul':'July',
    'Aug':'August','Sep':'Semtember','Oct':'October','Nov':'November','Dec':'December'
    }

for i in range(len(dates[2])):                                       #replacing date format based on dictionary 
   for j,k in replacement3_dict.items():
     if j in dates[2][i]:
       replaced_list_3a.append(dates[2][i].replace(j,k))

for i in range(len(replaced_list_3a)):                               #further fitting date format using re.sub() with proper regex
    replaced_list_3.append(re.sub("\s|th |nd |rd |th-|nd-|rd-|, ","-",replaced_list_3a[i]))


print('orignal dates:', dates[2])                                    # Printing orignal and replaced date format.
print('Replaced dates:', replaced_list_3)

replaced_list_4a=[]                                                  #Initializing list for extracted date format 4
replaced_list_4=[]

for i in range(len(dates[3])):                                       #Replacing date format using re.sub() with proper regex twice   
    replaced_list_4a.append(re.sub("\s|th, |nd, |rd, |, ","-",dates[3][i]))

for i in range(len(replaced_list_4a)):
    replaced_list_4.append(re.sub(r'(.*)-(\d{1,2})-(\d{4})', '\\2-\\1-\\3', replaced_list_4a[i]))


print('orignal dates:', dates[3])                                     # Printing orignal and replaced date format.
print('Replaced dates:', replaced_list_4)

replaced_list=[replaced_list_1,replaced_list_2,replaced_list_3,replaced_list_4]

print('Combined Orignal dates:')                                         #combining orignal and formated dates in single list
print( dates)
print('\nCombined Replaced dates:' )
print(replaced_list)

Flatten_date_list=[item for sublist in dates for item in sublist]                           #Flattening list
Flatten_replaced_list=[item for sublist in replaced_list for item in sublist]

for i in range(len(Flatten_date_list)):                                                     #converting data to standard xml format                                      
  data=data.replace(Flatten_date_list[i],f'<date std_date="{Flatten_replaced_list[i]}">{Flatten_date_list[i]}</date>')

data= '<output>\n' + data + '\n</output>'                                        

data

path2="/content/drive/MyDrive/sem2/Output.xml"                                        #storing data in Output.xmlfile

with open(path2,"w") as files:
  files.write(data)